project:
  type: website

website:
  title: "Try-it-together: Quarto Basics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:materials
      - text: "Hands-on Exercises"   
        menu:                        
          - href: hands-on/01-basics.qmd
          - href: hands-on/02-YAML.qmd
          - href: hands-on/03a-figures-tables.qmd
          - href: hands-on/03b-penguins.qmd
      
  sidebar:
    - id: materials
      title: "Materials"
      style: "docked"
      collapse-level: 2
      contents: 
        - session-01.qmd
        - href: hands-on/202410Quarto-handout-part1.zip
          text: Download Hands-on Exercises
execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

  revealjs: 
    theme: [default, custom.scss]
    width: 1920
    height: 1080
    slide-number: true
    footer: "[Try-it-together: Getting Started with Quarto](https://dpdong19.github.io/202410Quarto/)"
    chalkboard: false
    logo: "images/smu logo.png"
    incremental: true

editor: visual

