---
title: "Try-it-together: Getting Started with Quarto for Academic Writing"
format: html
date: 2024-10-15
author:
    name: Dong Danping
    email: dpdong@smu.edu.sg
    affiliation: Singapore Management University
---

## About This Course

This workshop is Part 1 of SMU Researcher Club's *Try-it-together Quarto Series*:

-   Part 1: [Try-it-together: Getting Started with Quarto for Academic Writing](https://smu-sg.libcal.com/event/5732787) on 15 Oct, 2024
-   Part 2: [Try-it-together: Generate Reports and Presentation with Quarto](https://smu-sg.libcal.com/event/5732794) on 22 Oct, 2024
-   Part 3: [Try-it-together: Building Your Research Website - From Quarto to the Web](https://smu-sg.libcal.com/event/5732795) on 29 Oct, 2024

In academic research, the journey from raw data to published findings often lacks transparency, posing significant challenges to reproducibility and trust in scientific research. This situation highlights the need for enhanced transparency and traceability within research methodologies.

The primary objective of this 3-part course is to equip participants with the necessary skills to use Quarto and RStudio to publish research in a transparent and reproducible way. These tools enable an integrated research workflow encompassing data cleaning, analysis, visualization, and publishing, producing verifiable research outputs and artifacts. They facilitate validation and replication of research findings, thereby enhancing the integrity and credibility of published work.

Quarto, an open-source scientific publishing system, allows researchers to weave together narrative text, code, mathematical formulas (using LATeX), and even citations to produce elegantly formatted output as documents, web pages, blog posts, books and other formats to cater to diverse publishing needs. While Quarto is also compatible with Python and Julia, the course will predominantly focus on its application in R programming.

## Lesson Objectives

1.  Understand the fundamental concepts of Quarto, including its role in promoting transparency and reproducibility in academic writing.
2.  Learn how to navigate the Quarto interface within RStudio, focusing on the basics of Markdown for structuring academic documents.
3.  Gain hands-on experience in creating simple Quarto documents by integrating narrative text, code, figures, and tables.

::: callout-note
*Prior experience with R is highly recommended for this course.*
:::

## Pre-session Preparation

Please ensure that you have completed the following activities before the workshop begin:

1.  [Download](https://posit.co/download/rstudio-desktop/) and install the latest version of R

2.  [Download](https://posit.co/download/rstudio-desktop/) and install the latest version of RStudio

3.  [Download](https://quarto.org/docs/download/index.html) and install the latest version of Quarto

    -   Although Quarto comes bundled with RStudio, it is often a few versions behind. The bundled version is version 1.22, while the latest version is on 1.5.55

4.  [Download the hands-on exercises](hands-on/202410Quarto-handout-part1.zip), which will be copied into your project folder during the lesson.

5.  Install these R packages. Copy the following code and paste it in the **Console** tab (left side pane of RStudio), and then press Enter.

    `install.packages(c( "tidyverse", "gt", "rmarkdown", "gtsummary", "palmerpenguins"))`

6.  You're ready to go! You can close Rstudio for now and see you soon!
